### PR TITLE
404 not found page

### LINKED ISSUE #28: Design a nice "404 Not Found" page for monolithic-layered app
Run `MonolithicApplication` and visit http://localhost:8080/drugs/404 (non-existent drug ID).

### Actual Demo

image

### Expected Demo

image

(or something like this)

### Guide

1. Return 404 status code instead of 500
2. Read https://www.baeldung.com/spring-boot-custom-error-page
3. Design 404.html page
4. Apply 404 page to all resources: Drugs, Pharmacies, Diseases, etc.

### PR DESCRIPTION
**Pull request by youngInnovator**
Closes #28

### CODE REVIEW

**Review by naXa777 — CHANGES_REQUESTED** [review]
@youngInnovator,
1. add this text to your PR description: `Closes #28`.
2. find all disabled tests related to #28 and enable them. For example see: https://github.com/aabarmin/epam-microservices-training-2022/blob/4856693c372c0025cf7dc08f6b3da732c42fe597/monolithic/monolithic-layered/src/test/java/com/epam/training/microservices/monolithic/web/SymptomControllerIT.java#L53
3.  if needed, write new tests as a part of this task.

**Comment by youngInnovator** [comment]
@naXa777 Suggested comments are addressed.

**Review by naXa777 — APPROVED** [review]

**Comment by youngInnovator** [comment]
@aabarmin Kindly approve and merge the MR, so I can claim it for #hacktoberfest :)

**Review by aabarmin — APPROVED** [review]
Looks good to me

**Pull request merged**
